### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by praisethemoon** [mehulrastogi/Deep-Belief-Network-pytorch#1]
https://github.com/mehulrastogi/Deep-Belief-Network-pytorch/blob/43b7187f0784d2bff7ac49536305d6bc95221da2/DBN.py#L35

Did you mean 
```py
 self.v_bias_mem = nn.Parameter(self.rbm_layers[-1].b.data) 
```
?

**Comment by mehulrastogi** [comment]
Yes, thank you for pointing out the syntax error. I have made the changes.
